### ISSUE TITLE
2 Controllers detected when emulating controller in hidraw mode

### ISSUE THREAD

**Issue by markubiak** [chrippa/ds4drv#46] opened 2014-11-05 03:00 UTC
Here's my issue: I use hidraw mode on Arch Linux, which is fine because BlueZ is new enough.  My main problem is that, when paired over bluetooth, 2 controllers are created by the system.  Here is Dolphin Emulator's controller configuration page using raw bluetooth mode:
![ds4drv1](https://cloud.githubusercontent.com/assets/2127493/4912036/70827470-6497-11e4-8808-74bf5772e0a7.png)
and under hidraw mode:
![ds4drv2](https://cloud.githubusercontent.com/assets/2127493/4912035/707fa18c-6497-11e4-8894-186f4a015c8f.png)
Now, this may not seem to be an issue, but in Borderlands 2, it crashes the entire game.  Yup.  Pretty bad bug, and I much prefer hidraw mode (by the way, you should submit a kernel patch for led support when you get the chance).  I'll see if I can find a workaround for Borderlands, but the long term solution would be to solve this double controller nonsense.  Yay linux.

**Comment by benmoran56** [comment] 2016-06-07 07:33
I just wanted to comment here, since this report is still open: 
I came across a comment from someone a while back that found a workaround to this problem. The initial roadblock is that it's not possible to delete the original hidraw device. However, the user discovered that he could simply copy the new virtual one over top of the original, so that it was no longer picked up by applications. I haven't looked into it at a technical level, but it sounds like a feasable solution.

**Comment by Mernst1** [comment] 2016-06-16 20:22
Have the same problem. A lot of games especially for games from steam but also for some emulators. There is no input recognizable i think because it grabs the wrong one "wireless Controller"

**Comment by Ryochan7** [comment] 2016-06-16 22:32
Another workaround that can probably be used is to change the permissions on the system created evdev device after grabbing it in order to disable all read access for new processes. That way, no application launched after ds4drv will have access to that device. Running `chmod 000 <device>` is a workaround that comes in handy under various circumstances. You can always reset the file permissions if you want to undo the change and allow other applications to have access to the device again; that probably wouldn't be desired in this case though.

**Comment by Mernst1** [comment] 2016-07-04 19:02
I tried the workaround above. It's really working when I change the permissions on the real hidraw evdev  device. The bad thing is that you always must repeat this steps to work again, when you disconnect the controller. Can someone maybe tell me how I can create a udev rule that always writes the permissions to 000 when the controller plugs in or gets connect.

**Comment by Ape** [comment] 2016-07-16 05:55
Closed as a duplicate of #45.

**Closed by Ape** 2016-07-16 05:55 UTC
