### ISSUE TITLE
IOError: [Errno 22] Invalid argument on Ubuntu

### ISSUE THREAD

**Issue by pasmai** [chrippa/ds4drv#67] opened 2016-02-24 16:38 UTC
I tried running ds4drv but I get this error. Eventhought bluetooth finds the controller and steam even recognizes it already.

```
Traceback (most recent call last):
  File "/usr/local/bin/ds4drv", line 9, in <module>
    load_entry_point('ds4drv==0.5.0', 'console_scripts', 'ds4drv')()
  File "build/bdist.linux-x86_64/egg/ds4drv/__main__.py", line 151, in main
  File "build/bdist.linux-x86_64/egg/ds4drv/__main__.py", line 120, in create_controller_thread
  File "build/bdist.linux-x86_64/egg/ds4drv/__main__.py", line 35, in __init__
  File "build/bdist.linux-x86_64/egg/ds4drv/__main__.py", line 93, in load_options
  File "build/bdist.linux-x86_64/egg/ds4drv/__main__.py", line 38, in fire_event
  File "build/bdist.linux-x86_64/egg/ds4drv/eventloop.py", line 86, in fire_event
  File "build/bdist.linux-x86_64/egg/ds4drv/eventloop.py", line 92, in process_events
  File "build/bdist.linux-x86_64/egg/ds4drv/actions/input.py", line 79, in load_options
  File "build/bdist.linux-x86_64/egg/ds4drv/uinput.py", line 425, in create_uinput_device
  File "build/bdist.linux-x86_64/egg/ds4drv/uinput.py", line 234, in __init__
  File "build/bdist.linux-x86_64/egg/ds4drv/uinput.py", line 290, in create_device
  File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 107, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument

```

**Comment by Ape** [comment] 2016-02-26 11:42
This is a duplicate of #66.

**Closed** 2016-03-04 15:13 UTC
