### ISSUE TITLE
Duplicate options in config file cause ds4drv to bail out

### ISSUE THREAD

**Issue by parkerlreed** [chrippa/ds4drv#63] opened 2015-11-24 15:52 UTC
````
[parker@lenovo ~]$ sudo ds4drv 
Traceback (most recent call last):
  File "/usr/bin/ds4drv", line 9, in <module>
    load_entry_point('ds4drv==0.5.0', 'console_scripts', 'ds4drv')()
  File "/usr/lib/python3.5/site-packages/ds4drv/__main__.py", line 132, in main
    options = load_options()
  File "/usr/lib/python3.5/site-packages/ds4drv/config.py", line 199, in load_options
    config.load(path)
  File "/usr/lib/python3.5/site-packages/ds4drv/config.py", line 74, in load
    self.read([filename])
  File "/usr/lib/python3.5/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.5/configparser.py", line 1090, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/etc/ds4drv.conf' [line 118]: option 'rel_wheelup' in section 'mapping:keyboard' already exists
````

The ds4drv.conf that comes with git has the options duplicated on line 118

**Comment by ntzrmtthihu777** [comment] 2015-12-28 09:00
I've ran into this same issue. Granted, its very simple to remove the offending lines, but what is in git should work out of box in my opinion.

**Comment by Ape** [comment] 2016-04-30 11:57
I can confirm. Does anybody want to create a fix for this?

**Closed** 2016-04-30 16:51 UTC
Labels: trivial

**Comment by Ciruxx** [comment] 2019-07-27 12:13
Hello!
Thank's for your job!
I comment this issue because the exact same error occurred downloading the tarball in the Arch Linux environment!
